stages: 
  - release
  - deploy

create-docker-image:
  stage: release
  image: docker:20
  tags: [akenarin-runner]
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags

variables:
  CONTAINER_NAME: 'akenarin-order-report-service' #ห้ามซ้ำกันกับเพื่อนๆ

auto_deploy_production:
  stage: deploy
  tags: [akenarin-runner]
  image: alpine:latest
  before_script:
    - apk update && apk add --no-cache openssh sshpass
  script:
    - sshpass -V
    - chmod -x ./deploy.sh
    - sh ./deploy.sh $CI_REGISTRY_USER $CI_REGISTRY_PASSWORD $CI_REGISTRY $CONTAINER_NAME $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags